### ISSUE TITLE
About the training script 

### ISSUE THREAD

**Issue by darkpromise98** [billpsomas/Metrix_ICLR22#1]
Hello, a nice work for metric learning !
I'm interesting for the method and want to re-produce the results. Can you provide the training script for each dataset (e.g., CUB200 and CARS196) and baseline losses (e.g, MS and Contrastive loss) ? The repo lacks further details about training parameters now. 

Looking forward to receiving your response. Thanks in advance.

**Comment by billpsomas** [comment]
Hello @darkpromise98!

Thank you for the reminder. We are about to update the repo with more code and a more detailed README,

**Comment by KeyaoZhao** [comment]
> 



> Hello @darkpromise98!
> 
> Thank you for the reminder. We are about to update the repo with more code and a more detailed README,

@billpsomas Hello! I'm also interested in this method! Can you provide the code of MS loss? Thanks a lot!!

**Comment by billpsomas** [comment]
Hello @KeyaoZhao, the code will be released really soon. I am currently working on it. Thanks for asking!!!
